feat: implemented serializers for line item container and result cont…
oat-sa/lib-lti1p3-ags pull request #50
Opened 2021-11-17 15:42 UTC by gyszucs

feat: implemented serializers for `LineItemContainer` and `ResultContainer`

target release: `1.4.0`

2021-11-18 08:14 UTC, ArnaskasparasOAT approved these changes

2021-11-18 08:20 UTC, mike-ionut-mihai-sandu-tao reviewed
left some minor comments

2021-11-18 08:20 UTC, mike-ionut-mihai-sandu-tao commented on src/Model/LineItem/LineItemContainer.php
> +    public function jsonSerialize(): array
should we use the symfony normalizer or a formatter object ?

2021-11-18 08:20 UTC, mike-ionut-mihai-sandu-tao commented on src/Model/Result/ResultContainer.php
> +    public function jsonSerialize(): array
having the same function in multiple parts ? 
can we put this in  a trait for refactor it as a formater / normalizer ?

2021-11-18 08:20 UTC, mike-ionut-mihai-sandu-tao commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +        return json_encode($container);
do we care if the encoding will fail ?

2021-11-18 08:20 UTC, mike-ionut-mihai-sandu-tao commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +        foreach ($data['lineItems'] ?? [] as $lineItemData) {
should we move this part to the collection 
in a function like `fromArray` ?

2021-11-18 08:20 UTC, mike-ionut-mihai-sandu-tao commented on src/Serializer/Result/ResultContainerSerializer.php
> +class ResultContainerSerializer implements ResultContainerSerializerInterface
same code blocks as  LineItemContainerSerializer , should we try to refactor this ?

2021-11-18 08:20 UTC, mike-ionut-mihai-sandu-tao commented on src/Serializer/Result/ResultContainerSerializer.php
> +class ResultContainerSerializer implements ResultContainerSerializerInterface
or it is a different domain ?

2021-11-18 08:23 UTC, mike-ionut-mihai-sandu-tao commented
can you please edit the initial comment and add the ticket and also the AC's ? 
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-11-18 08:30 UTC, andreluizmachado reviewed
Hey Nice Job! I just left a question for you.

2021-11-18 08:30 UTC, andreluizmachado commented on src/Model/LineItem/LineItemContainerInterface.php
> +interface LineItemContainerInterface extends JsonSerializable
why don't you instead of inherit this interface, you use the interface JsonSerializable directly on the concrete objects? don't you think that this can go against to the Interface segregation principle?

2021-11-18 08:59 UTC, wazelin commented on src/Model/LineItem/LineItemContainer.php
> +    public function jsonSerialize(): array
As much as I love the symfony's normalizer, I don't think it's a good idea to enforce the users of the AGS library to use it.

2021-11-18 09:03 UTC, wazelin requested changes

2021-11-18 09:03 UTC, wazelin commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +        return json_encode($container);
Considering that, `json_encode()` doesn't always return `string` ;)

2021-11-18 09:14 UTC, gyszucs commented on src/Model/LineItem/LineItemContainer.php
> +    public function jsonSerialize(): array
Totally agree.

2021-11-18 09:16 UTC, gyszucs commented on src/Model/Result/ResultContainer.php
> +    public function jsonSerialize(): array
It would be a good idea but in this case, it does not worth it IMO. The content of the returned array will be different each time.

2021-11-18 09:18 UTC, gyszucs commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +        return json_encode($container);
Good catch. Looks like the previously created serializers will have to fixed also.

2021-11-18 09:25 UTC, gyszucs commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +        foreach ($data['lineItems'] ?? [] as $lineItemData) {
Not really since in the `foreach`, the item factory service is used the create `LineItem`.

2021-11-18 09:26 UTC, gyszucs commented on src/Serializer/Result/ResultContainerSerializer.php
> +class ResultContainerSerializer implements ResultContainerSerializerInterface
yeap, different domain. The inputs and outputs of the methods are different.

2021-11-18 09:45 UTC, gyszucs commented on src/Model/LineItem/LineItemContainerInterface.php
> +interface LineItemContainerInterface extends JsonSerializable
> why don't you instead of inherit this interface, you use the interface JsonSerializable directly on the concrete objects? don't you think that this can go against to the Interface segregation principle?

Good question. The main reason is to be consequent with the existing code. Anyway, how would you make sure that any implementation of `LineItemContainerInterface` does implements `jsonSerialize` method? Since in the services we depend on `LineItemContainerInterface`.

2021-11-22 14:03 UTC, wazelin requested changes

2021-11-22 14:03 UTC, wazelin commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +        }
WDYT of implementing a generic Json data serializer/deserializer, and then reusing it here and in other specific serializer implementations?

```php
class JsonSerializer
{
    /**
     * @throws LtiExceptionInterface
     */
    public function serialize(JsonSerializable $object): string
    {
        $json = json_encode($object);
        $this->assertNoJsonError();

        return $json;
    }

    /**
     * @throws LtiExceptionInterface
     */
    public function deserialize(): array
    {
        $data = json_decode($data, true);
        $this->assertNoJsonError();

        return $data;
    }

    /**
     * @throws LtiExceptionInterface
     */
    private function assertNoJsonError(): void
    {
       if (JSON_ERROR_NONE !== json_last_error()) {
            throw new LtiException(
                sprintf('Error during line item container serialization: %s', json_last_error_msg())
            );
        }
    }
}
```

Something like that, and then removing all the json error checks all over the place.
```suggestion

    /** @var JsonSerializer */
    private $jsonSerializer;

    public function __construct(?LineItemFactoryInterface $factory = null, JsonSerializer $jsonSerializer = null)
    {
        $this->lineItemFactory = $factory ?? new LineItemFactory();
        $this->jsonSerializer = $jsonSerializer ?? new JsonSerializer();
    }

    /**
     * @throws LtiExceptionInterface
     */
    public function serialize(LineItemContainerInterface $container): string
    {
        return $this->jsonSerializer->serialize($container);
    }

    /**
     * @throws LtiExceptionInterface
     */
    public function deserialize(string $data): LineItemContainerInterface
    {
        $data = $this->jsonSerializer->deserialize($data);
```

2021-11-23 09:17 UTC, gyszucs commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +        }
Good idea, definitely doable. Less code repetition. ;)

2021-11-23 14:52 UTC, wazelin requested changes

2021-11-30 08:30 UTC, gyszucs commented on src/Serializer/LineItem/LineItemCollectionSerializer.php
> +            throw new LtiException(
Done

2021-11-30 08:31 UTC, siwane approved these changes

2021-11-30 12:02 UTC, wazelin approved these changes
LGTM, thanks a lot for the PR and your patience!

2021-12-14 20:16 UTC, ekkinox commented
nice addition @gyszucs , thx :)

2021-12-14 20:16 UTC, ekkinox approved these changes

2021-12-14 20:44 UTC, ekkinox commented on src/Model/Result/ResultContainer.php
> +    public function jsonSerialize(): array
it's an interface implmentation

2021-12-14 20:45 UTC, ekkinox commented on src/Model/LineItem/LineItemContainerInterface.php
> +interface LineItemContainerInterface extends JsonSerializable
more robust indeed on interface level, but yes it's a BC

2021-12-14 20:48 UTC, ekkinox commented on src/Serializer/JsonSerializerInterface.php
> +interface JsonSerializerInterface
I understand this interface for the sake of extensibility, but I doubt it's usefull for users to provide another json encore / decode implementation than yours.

I would have just provided JsonSerializerInterface, no interface, and build it in serializers constructors

that being said, you already did all the job, so lets keep this ! :)

2021-12-14 20:50 UTC, ekkinox commented on src/Serializer/LineItem/LineItemCollectionSerializer.php
> +        ?LineItemFactoryInterface $factory = null,
could you make the constructor parameter name and the class property name match ?

this comment applies to all similar changes (even if I personally don't see the need)

2021-12-14 20:52 UTC, ekkinox commented on src/Serializer/LineItem/LineItemContainerSerializer.php
> +                0,
why not using the original exception code (->getCode()) instead of this arbitrary value ?

2021-12-14 20:54 UTC, ekkinox requested changes
nice addition @gyszucs , thx !

I added a few comments to check

2022-01-11 16:29 UTC, gyszucs commented
> nice addition @gyszucs , thx !
> 
> I added a few comments to check

Thanks. Change requests are implemented.

2022-01-11 16:36 UTC, merged